ManejoIncidente.Web/Controllers/PrioridadController.cs
using ManejoIncidente.Logica.Prioridades;
using ManejoIncidente.Logica.Slas;
using ManejoIncidente.Modelos;
using ManejoIncidente.Web.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ManejoIncidente.Web.Controllers
{
    public class PrioridadController : BaseController
    {
        private readonly PrioridadLogica _prioridadLogica;
        private readonly SlaLogica _slaLogica;
        public PrioridadController()
        {
            _prioridadLogica = new PrioridadLogica();
            _slaLogica = new SlaLogica();
        }
        [VerifySession]
        // GET: Prioridad
        public ActionResult Insertar()
        {
            try
            {
                var modelo = new PrioridadVM
                {
                    Slas = _slaLogica.ConsultarSla(0)
                };
                return View(modelo);
            }
            catch (Exception ex)
            {
                MensajeError = "Error cargando pantalla insertar";
                return RedirectToAction("Prioridades");
            }
        }

        [HttpPost, VerifySession]
        public ActionResult Insertar(PrioridadVM prioridadVM)
        {
            try
            {
                var modelo = new Prioridad()
                {
                    CreadoPor = LoginHelper.ID,
                    FechaIngreso = DateTimeOffset.Now,
                    Nombre = prioridadVM.Nombre,
                    SlaId = prioridadVM.SlaId,
                    Estatus = "A"
                };
                _prioridadLogica.InsertarPrioridad(modelo);
                MensajeSucces = "Priodidad Insertada";
                return RedirectToAction("Prioridades");
            }
            catch (Exception ex)
            {
                MensajeError = "Error Insertando";
                return RedirectToAction("Prioridades");
            }
        }

        [VerifySession]
        public ActionResult Prioridades()
        {
            try
            {
                var prioridades = _prioridadLogica.ConsultarPrioridad(0);
                var modelo = new List<PrioridadVM>();
                string sla = "";
                foreach (var item in prioridades)
                {

                    var slas = _slaLogica.ConsultarSla(item.SlaId);
                    if (slas.Count.Equals(0)) sla = "No disponible";
                    else sla = slas[0].Descripcion;
                    modelo.Add(new PrioridadVM
                    {
                        Sla = sla,
                        Nombre = item.Nombre,
                        PrioridadId = item.PrioridadId
                    });
                }
                if (prioridades.Count.Equals(0)) MensajeInfo = "No Hay Prioridades Registradas";
                ViewData["GOOD"] = MensajeSucces;
                ViewData["ERROR"] = MensajeError;
                ViewData["INFO"] = MensajeInfo;
                LiberarMensajes();
                return View(modelo);
            }
            catch (Exception ex)
            {
                MensajeError = "Error cargando pantalla de Prioridades";
                return RedirectToAction("Index", "Home");
            }
        }

        [VerifySession]
        public ActionResult Actualizar(int id)
        {
            try
            {
                var prioridad = _prioridadLogica.ConsultarPrioridad(id)[0];
                var slas = _slaLogica.ConsultarSla(0);
                var modelo = new PrioridadVM()
                {
                    Nombre = prioridad.Nombre,
                    Slas = slas,
                    SlaId = prioridad.SlaId,
                    PrioridadId = prioridad.PrioridadId
                };

                return View(modelo);
            }
            catch (Exception ex)
            {
                MensajeError = "Error cargando pantalla actualizar";
                return RedirectToAction("Puestos");
            }
        }

        [HttpPost, VerifySession]
        public ActionResult Actualizar(PrioridadVM prioridadVM)
        {
            try
            {
                var modelo = new Prioridad()
                {
                    PrioridadId = prioridadVM.PrioridadId,
                    Nombre = prioridadVM.Nombre,
                    SlaId = prioridadVM.SlaId,
                    ModificadoPor = LoginHelper.ID,
                    FechaModificacion = DateTimeOffset.Now
                };
                _prioridadLogica.ActualizarPrioridad(modelo);
                MensajeSucces = "Prioridad Actulizada";
                return RedirectToAction("Prioridades");
            }
            catch (Exception ex)
            {
                MensajeError = "Error actualizando";
                return RedirectToAction("Prioridades");
            }
        }

        [VerifySession]
        public ActionResult Eliminar(int id)
        {
            try
            {
                var prioridad = _prioridadLogica.ConsultarPrioridad(id)[0];
                var slas = _slaLogica.ConsultarSla(prioridad.SlaId);
                string sla = "";
                if (slas.Count.Equals(0)) sla = "No disponible";
                else sla = slas[0].Descripcion;
                var modelo = new PrioridadVM()
                {
                    Nombre = prioridad.Nombre,
                    Sla = sla,
                    PrioridadId = prioridad.PrioridadId
                };
                return View(modelo);
            }
            catch (Exception ex)
            {
                MensajeError = "Error cargando pantalla de Eliminar";
                return RedirectToAction("Prioridades");
            }
        }

        [HttpPost, VerifySession]
        public ActionResult Eliminar(PrioridadVM prioridadVM)
        {
            try
            {
                _prioridadLogica.EliminarPrioridad(prioridadVM.PrioridadId);
                MensajeSucces = "Prioridad Elimanda";
                return RedirectToAction("Prioridades");
            }
            catch (Exception ex)
            {
                MensajeError = "Error Eliminando";
                return RedirectToAction("Prioridades");
            }
        }

    }
}

ManejoIncidente.Web/Controllers/SlaController.cs
using ManejoIncidente.Logica.Slas;
using ManejoIncidente.Modelos;
using ManejoIncidente.Web.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ManejoIncidente.Web.Controllers
{
    public class SlaController : BaseController
    {
        private readonly SlaLogica _slaLogica;
        public SlaController()
        {
            _slaLogica = new SlaLogica();
        }
        // GET: Sla
        [VerifySession]
        public ActionResult Insertar()
        {
            try
            {
                return View();
            }
            catch (Exception)
            {
                MensajeError = "Error cargando pantalla insertar";
                return RedirectToAction("Slas");
            }
        }

        [HttpPost, VerifySession]
        public ActionResult Insertar(SlaVM slaVM)
        {
            try
            {
                var modelo = new Sla()
                {
                    CreadoPor = LoginHelper.ID,
                    CantidadHoras = slaVM.CantidadHoras,
                    Estatus = "A",
                    Descripcion = slaVM.Descripcion,
                    FechaIngreso = DateTimeOffset.Now
                };
                _slaLogica.InsertarSla(modelo);
                MensajeSucces = "Sla Insertado";
                return RedirectToAction("Slas");
            }
            catch (Exception)
            {
                MensajeError = "Erro Insertando";
                return RedirectToAction("Slas");
            }
        }

        [VerifySession]
        public ActionResult Slas()
        {
            try
            {
                var Slas = _slaLogica.ConsultarSla(0);
                var modelo = new List<SlaVM>();
                foreach (var item in Slas)
                {
                    modelo.Add(new SlaVM
                    {
                        SlaId = item.SlaId,
                        CantidadHoras = item.CantidadHoras,
                        Descripcion = item.Descripcion
                    });
                }
                if (Slas.Count.Equals(0)) MensajeInfo = "No Hay Slas Registrados";
                ViewData["GOOD"] = MensajeSucces;
                ViewData["ERROR"] = MensajeError;
                ViewData["INFO"] = MensajeInfo;
                LiberarMensajes();
                return View(modelo);
            }
            catch (Exception ex)
            {
                MensajeError = "Error cargando pantalla Slas";
                return RedirectToAction("Index", "Home");
            }
        }

        [VerifySession]
        public ActionResult Actualizar(int id)
        {
            try
            {
                var sla = _slaLogica.ConsultarSla(id)[0];
                var modelo = new SlaVM()
                {
                    Descripcion = sla.Descripcion,
                    CantidadHoras = sla.CantidadHoras,
                    SlaId = sla.SlaId
                };
                return View(modelo);
            }
            catch (Exception ex)
            {
                MensajeError = "Error cargando pantalla actualizar";
                return RedirectToAction("Slas");
            }
        }

        [HttpPost, VerifySession]
        public ActionResult Actualizar(SlaVM slaVM)
        {
            try
            {
                var modelo = new Sla()
                {
                    ModificadoPor = LoginHelper.ID,
                    CantidadHoras = slaVM.CantidadHoras,
                    Descripcion = slaVM.Descripcion,
                    FechaModificacion = DateTimeOffset.Now,
                    SlaId = slaVM.SlaId
                };
                _slaLogica.ActualizarSla(modelo);
                MensajeSucces = "Sla Actualizado";
                return RedirectToAction("Slas");
            }
            catch (Exception)
            {
                MensajeError = "Error Actualizando";
                return RedirectToAction("Slas");
            }
        }

        [VerifySession]
        public ActionResult Eliminar(int id)
        {
            try
            {
                var sla = _slaLogica.ConsultarSla(id)[0];
                var modelo = new SlaVM()
                {
                    Descripcion = sla.Descripcion,
                    CantidadHoras = sla.CantidadHoras,
                    SlaId = sla.SlaId
                };
                return View(modelo);
            }
            catch (Exception ex)
            {
                MensajeError = "Error cargando pantalla eliminar";
                return RedirectToAction("Slas");
            }
        }

        [HttpPost, VerifySession]
        public ActionResult Eliminar(SlaVM slaVM)
        {
            try
            {
                _slaLogica.ElimiarSla(slaVM.SlaId);
                MensajeSucces = "Sla Elimando";
                return RedirectToAction("Slas");
            }
            catch (Exception ex)
            {
                MensajeError = "Error elimnando";
                return RedirectToAction("Slas");
            }
        }
    }
}

ManejoIncidente.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Incidentes Mordan</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
        <div class="container">
            @Html.ActionLink("Incidentes Mordan", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                <ul class="nav navbar-nav">
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            Usuarios
                        </a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <a class="dropdown-item" href="@Url.Action("InsertarUsuario","Usuarios")">Nuevo Usuario</a>
                            <div class="dropdown-divider"></div>
                            <a class="dropdown-item" href="@Url.Action("Usuarios","Usuarios")">Usuarios</a>
                        </div>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            Departamentos
                        </a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <a class="dropdown-item" href="@Url.Action("Insertar","Departamentos")">Nuevo Departamento</a>
                            <div class="dropdown-divider"></div>
                            <a class="dropdown-item" href="@Url.Action("Departamentos","Departamentos")">Departamentos</a>
                        </div>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            Puestos
                        </a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <a class="dropdown-item" href="@Url.Action("Insertar","Puestos")">Nuevo Puesto</a>
                            <div class="dropdown-divider"></div>
                            <a class="dropdown-item" href="@Url.Action("Puestos","Puestos")">Puestos</a>
                        </div>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            Sla
                        </a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <a class="dropdown-item" href="@Url.Action("Insertar","Sla")">Nuevo Sla</a>
                            <div class="dropdown-divider"></div>
                            <a class="dropdown-item" href="@Url.Action("Slas","Sla")">Slas</a>
                        </div>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            Prioridad
                        </a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <a class="dropdown-item" href="@Url.Action("Insertar","Prioridad")">Nueva Prioridad</a>
                            <div class="dropdown-divider"></div>
                            <a class="dropdown-item" href="@Url.Action("Prioridades","Prioridad")">Prioridades</a>
                        </div>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            Incidente
                        </a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <a class="dropdown-item" href="@Url.Action("Registrar","Incidentes")">Nuevo Incidente</a>
                            <div class="dropdown-divider"></div>
                            <a class="dropdown-item" href="@Url.Action("Incidentes","Incidentes")">Todos Los Incidentes</a>
                            <div class="dropdown-divider"></div>
                            <a class="dropdown-item" href=" @Url.Action("InidentesPendientes", "Incidentes") ">Incidentes No Asignados</a>
                            <div class="dropdown-divider"></div>
                            <a class="dropdown-item" href=" @Url.Action("Propios", "Incidentes") ">Mis Incidentes</a>
                            <div class="dropdown-divider"></div>
                            <a class="dropdown-item" href="@Url.Action("Pendientes","Incidentes")">Mis Incidentes Pendientes</a>
                            <div class="dropdown-divider"></div>
                            <a class="dropdown-item" href="@Url.Action("Completados","Incidentes")">Mis Incidentes Completados</a>
                            <div class="dropdown-divider"></div>
                            <a class="dropdown-item" href="@Url.Action("Solicutudes","Incidentes")">Mis Solicitudes</a>

                        </div>
                    </li>

                    <li class="nav-item dropdown">

                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">

                            <img src="~/Content/img/usuario.png" style="height:20px" />
                            @if (Session["Usuario"] != null)
                            {
                                @ManejoIncidente.Web.LoginHelper.NombreUsuario;
                            }
                            <span class="caret"></span>
                        </a>

                        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <a class="dropdown-item" href="@Url.Content("~/Login/Logout")">Cerrar Sesión</a>

                        </div>
                    </li>


                </ul>
            </div>
        </div>
    </nav>

    @if (ViewData["ERROR"] != null)
    {
        <div class="container">
            <div class="alert alert-danger">
                @ViewData["ERROR"]
            </div>
        </div>
    }
    @if (ViewData["GOOD"] != null)
    {

        <div class="container">
            <div class="alert alert-success">
                @ViewData["GOOD"]
            </div>
        </div>
    }
    @if (ViewData["INFO"] != null)
    {

        <div class="container">
            <div class="alert alert-info">
                @ViewData["INFO"]
            </div>
        </div>
    }

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Jose Mordan</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

ManejoIncidente.Web/Views/Shared/_LayoutLogin.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Incidentes Mordan</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
        <div class="container">
            @Html.ActionLink("Incidentes Mordan", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                <ul class="nav navbar-nav">
                   
                </ul>
            </div>
        </div>
    </nav>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Jose Mordan</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>